### ISSUE TITLE
Error "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by frankbracq** [BALKANGraph/FamilyTreeJS#132]
Hi,

I'm using the trial version. From time to time, I get the following error

Uncaught RangeError: Maximum call stack size exceeded
    at o.manager._setCollpasedProperty (familytree.js:1:233217)
    at o.manager._initNode (familytree.js:1:234539)
    at o.manager._iterate (familytree.js:1:235760)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    at o.manager._iterate (familytree.js:1:237685)
    
  Thank you in advance for your help

**Comment by ZornitsaPesheva** [comment]
Your trial may have expired, but if you think this is not the reason, please create a code example to isolate the issue:
https://code.balkan.app/familytreejs/getting-started#JS

**Comment by frankbracq** [comment]
I mistakenly changed something in my code. Error has nothing to do with FamilyTreeJS!
